/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Dis_A_aliases.h"
#include "Dis_A.h"
#include "Dis_B_aliases.h"
#include "Dis_B.h"
#include "Dis_C_aliases.h"
#include "Dis_C.h"
#include "Dis_D_aliases.h"
#include "Dis_D.h"
#include "Dis_E_aliases.h"
#include "Dis_E.h"
#include "Dis_F_aliases.h"
#include "Dis_F.h"
#include "Dis_G_aliases.h"
#include "Dis_G.h"
#include "Dis_DP_aliases.h"
#include "Dis_DP.h"
#include "Dis_D1_aliases.h"
#include "Dis_D1.h"
#include "Dis_D2_aliases.h"
#include "Dis_D2.h"
#include "Dis_D3_aliases.h"
#include "Dis_D3.h"
#include "Dis_D4_aliases.h"
#include "Dis_D4.h"
#include "Clock_2.h"
#include "isr_2.h"
#include "isr_7Seg.h"
#include "Display_Clk.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

